---
- name: Provision developer VMs
  hosts: baremetaltest
  roles:
    - role: cloudflare_application
      vars:
        allowed_emails: 
          - emil.h.harvey@outlook.com
        web_address: "eharvey-projectv-dev.{{ domain.root }}"
        local_port: "8080"
        application_name: "eharvey-projectV-dev"
        cloudflare_zone: "{{ cloudflare.zone }}"
        cloudflare_api_token: "{{ cloudflare.api_token }}"
        cloudflare_account: "{{ cloudflare.account }}"