---
- name: Create developer VMs
  hosts: baremetaltest
  vars_files: 
    - "./project-v/facts.yaml"
  tasks:
    - name: Create Developer VMS
      ansible.builtin.include_role: 
        name: lxdvm
      vars:
        name: "{{ vm_config.username }}"
        memory: 1GB
        group: "projectv-devs"
        facts:
          dev_email: "{{ vm_config.email }}"
          dev_username: "{{ vm_config.email | split('@') | first }}"
      loop: "{{ devs }}"
      loop_control:
        loop_var: vm_config


- name: Provision developer VMs
  hosts: "projectv-devs"
  roles:
    - onboarding
    - role: code-server
      vars:
        enable_sudo: true
    - role: cloudflare_application
      vars:
        allowed_emails: 
          - "{{ dev_email }}"
          - emil.h.harvey@outlook.com
        web_address: "eharvey-projectv-dev.{{ domain.root }}"
        local_port: "8080"
        application_name: "eharvey-projectV-dev"
        cloudflare_zone: "{{ cloudflare.zone }}"
        cloudflare_api_token: "{{ cloudflare.api_token }}"
        cloudflare_account: "{{ cloudflare.account }}"
