---
- name: Configure tailscale
  hosts: unprovisioned_baremetals
  roles:
    - tailscale
  vars:
    static_ips:
      baremetal0: # Set static IP here
    ansible_host: "{{ static_ips[inventory_hostname] }}"

- name: Configure ZFS pools on capable devices
  hosts: unprovisioned_baremetals
  tasks:
    - name: Configure ZFS
      ansible.builtin.include_role:
        name: zfs
      when: zfs is defined

- name: Provision initial machine
  hosts: unprovisioned_baremetals
  roles:
    - onboarding
    - lxd     
    